import React, { useState, useEffect } from 'react';
import DocLayout from '../../components/layout/DocLayout';
import { EconomyConfigEngine } from '../../engines/system/EconomyConfigEngine';

const ReferralPolicy: React.FC = () => {
  const [config, setConfig] = useState<any>(null);

  useEffect(() => {
    EconomyConfigEngine.getConfig().then(setConfig);
  }, []);

  return (
    <DocLayout title="Referral Policy" lastUpdated="June 22, 2026">
      <section>
        <h2>1. The PulseEarn Referral Program</h2>
        <p>
          Our referral program allows users to earn bonuses by inviting new participants to the platform. We value genuine community growth and reward referrers for their onboarding efforts.
        </p>
      </section>

      <section>
        <h2>2. Reward Structure</h2>
        <p>
          The standard referral reward structure is as follows:
        </p>
        <ul>
          <li><strong>Referrer Bonus:</strong> {config?.rewards?.referralBonusPoints || 50} PTS (${((config?.rewards?.referralBonusPoints || 50) / 1000).toFixed(2)}) for every verified new user.</li>
          <li><strong>Referee Bonus:</strong> {config?.rewards?.welcomeBonusPoints || 30} PTS (${((config?.rewards?.welcomeBonusPoints || 30) / 1000).toFixed(2)}) for joining via a valid referral code.</li>
          <li><strong>Passive Income:</strong> Referrers may earn an additional 5% commission on all campaign earnings generated by their referrals (depending on user level).</li>
        </ul>
      </section>

      <section>
        <h2>3. Qualification Requirements</h2>
        <p>
          For a referral reward to be successfully distributed:
        </p>
        <ul>
          <li>The referee must sign up using a valid referral link or code.</li>
          <li>The referee must verify their email address.</li>
          <li>The referee must complete at least one verified campaign or platform task.</li>
        </ul>
      </section>

      <section>
        <h2>4. Prohibited Behavior</h2>
        <p>
          To maintain the integrity of the program, the following are strictly prohibited:
        </p>
        <ul>
          <li><strong>Self-Referral:</strong> Creating multiple accounts to refer yourself.</li>
          <li><strong>Incentivized Traffic:</strong> Paying third parties to sign up using your link.</li>
          <li><strong>Spam:</strong> Distributing referral links through unsolicited messages or automated bots.</li>
          <li><strong>Misleading Content:</strong> Promising unrealistic rewards to induce signups.</li>
        </ul>
      </section>

      <section>
        <h2>5. Enforcement</h2>
        <p>
          Any user found violating the Referral Policy will have their referral bonuses revoked and may face permanent account suspension. Our fraud detection systems monitor IP patterns, device fingerprints, and behavioral data to identify referral abuse.
        </p>
      </section>
    </DocLayout>
  );
};

export default ReferralPolicy;
