import { useCallback, useEffect, useState } from 'react';
import { auth } from '../../firebase/config';
import { safeFetch } from '../../utils/api';

export default function PSEmineAdmin() {
  const [stats, setStats] = useState<any>(null);
  const [reason, setReason] = useState('');
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [settlements, setSettlements] = useState<any[]>([]);
  const load = useCallback(async () => { const token = await auth.currentUser?.getIdToken(); if (!token) return; const headers = { Authorization: `Bearer ${token}` }; const [overview, queue] = await Promise.all([safeFetch('/api/admin/mine/overview', { headers }), safeFetch('/api/admin/mine/settlements', { headers })]); if (overview.success) setStats(overview.stats); else setMessage(overview.error || 'Unable to load campaign operations.'); if (queue.success) setSettlements(queue.settlements || []); }, []);
  useEffect(() => { void load(); }, [load]);
  const act = async (action: string) => { setBusy(true); setMessage(''); const token = await auth.currentUser?.getIdToken(); const result = await safeFetch('/api/admin/mine/campaign/action', { method: 'POST', headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify({ action, reason }) }); setMessage(result.success ? `Campaign ${action} request completed.` : result.error || 'Action failed.'); await load(); setBusy(false); };
  return <main className="psemine-admin-page"><div className="psemine-shell"><header className="psemine-dashboard-heading"><div><span className="psemine-eyebrow">PSEmine operations</span><h1>Campaign control</h1><p>Authorized operations only. Sensitive provider and wallet secrets stay server-side.</p></div></header><section className="psemine-dashboard-grid psemine-dashboard-grid--three">{[['Campaign status', stats?.campaignStatus || 'Unavailable'], ['Active miners', stats?.activeMiners ?? 'Unavailable'], ['Accrued liability', stats ? `£${Number(stats.totalAccruedLiabilityGBP || 0).toFixed(2)}` : 'Unavailable']].map(([label, value]) => <article className="psemine-dashboard-card" key={label}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="psemine-dashboard-card psemine-admin-controls"><h2>Lifecycle controls</h2><p>Starting enables purchases and accrual. Stopping disables new activity. Settlement freezes accrual and prepares the payout queue.</p><label>Audit reason<input value={reason} onChange={event => setReason(event.target.value)} placeholder="Why is this action being taken?" /></label><div className="psemine-hero-actions"><button disabled={busy} onClick={() => void act('start')}>Start campaign</button><button disabled={busy} onClick={() => void act('stop')}>Stop campaign</button><button disabled={busy} onClick={() => void act('settle')}>Begin settlement</button><button disabled={busy} onClick={() => void act('shutdown')}>Archive campaign</button></div>{message && <p role="status">{message}</p>}</section><section className="psemine-dashboard-card"><h2>Settlement queue</h2><p>{settlements.length ? `${settlements.length} settlement record${settlements.length === 1 ? '' : 's'} available for review.` : 'No settlement snapshots have been created.'}</p>{settlements.slice(0, 8).map(item => <div className="psemine-wallet-row" key={item.settlementId}><span>{item.settlementId}</span><strong>{item.status || 'pending'}</strong></div>)}</section></div></main>;
}
